// Type declarations for the WASM parser module generated by wasm-bindgen

export function parse_excel(data: Uint8Array): unknown;
export function initSync(module?: BufferSource | WebAssembly.Module): void;
export default function init(module_or_path?: string | URL | Request | Response | BufferSource | WebAssembly.Module): Promise<void>;
