import type { Project, Register, Field, AddressBlock, MemoryMap } from "@register-manager/shared";
import { parseNumber, toHex, getFieldAccess } from "@register-manager/shared";

interface HTMLDocOptions {
  title?: string;
  includeStyles?: boolean;
  includeTOC?: boolean;
  theme?: "light" | "dark";
}

/**
 * Generate HTML documentation from IP-XACT project
 */
export function generateHTMLDoc(project: Project, options: HTMLDocOptions = {}): string {
  const {
    title = project.displayName || project.name,
    includeStyles = true,
    includeTOC = true,
    theme = "light",
  } = options;

  const html: string[] = [];

  // HTML header
  html.push(`<!DOCTYPE html>`);
  html.push(`<html lang="en">`);
  html.push(`<head>`);
  html.push(`  <meta charset="UTF-8">`);
  html.push(`  <meta name="viewport" content="width=device-width, initial-scale=1.0">`);
  html.push(`  <title>${escapeHtml(title)} - Register Documentation</title>`);

  if (includeStyles) {
    html.push(getStyles(theme));
  }

  html.push(`</head>`);
  html.push(`<body>`);

  // Header
  html.push(`  <header>`);
  html.push(`    <h1>${escapeHtml(title)}</h1>`);
  html.push(`    <p class="subtitle">Register Documentation</p>`);
  html.push(`    <div class="meta">`);
  html.push(`      <span><strong>VLNV:</strong> ${escapeHtml(project.vlnv.vendor)}:${escapeHtml(project.vlnv.library)}:${escapeHtml(project.vlnv.name)}:${escapeHtml(project.vlnv.version)}</span>`);
  html.push(`      <span><strong>Generated:</strong> ${new Date().toLocaleString()}</span>`);
  html.push(`    </div>`);
  if (project.description) {
    html.push(`    <p class="description">${escapeHtml(project.description)}</p>`);
  }
  html.push(`  </header>`);

  html.push(`  <main>`);

  // Table of Contents
  if (includeTOC) {
    html.push(generateTOC(project));
  }

  // Memory Maps
  project.memoryMaps?.forEach((memoryMap, idx) => {
    html.push(generateMemoryMapSection(memoryMap, idx));
  });

  html.push(`  </main>`);

  // Footer
  html.push(`  <footer>`);
  html.push(`    <p>Generated by Register Manager | ${new Date().toISOString()}</p>`);
  html.push(`  </footer>`);

  html.push(`</body>`);
  html.push(`</html>`);

  return html.join("\n");
}

function generateTOC(project: Project): string {
  const lines: string[] = [];

  lines.push(`    <nav class="toc">`);
  lines.push(`      <h2>Table of Contents</h2>`);
  lines.push(`      <ul>`);

  project.memoryMaps?.forEach((mm, mmIdx) => {
    lines.push(`        <li><a href="#mm-${mmIdx}">${escapeHtml(mm.displayName || mm.name)}</a>`);
    if (mm.addressBlocks && mm.addressBlocks.length > 0) {
      lines.push(`          <ul>`);
      mm.addressBlocks.forEach((ab, abIdx) => {
        lines.push(`            <li><a href="#ab-${mmIdx}-${abIdx}">${escapeHtml(ab.displayName || ab.name)}</a></li>`);
      });
      lines.push(`          </ul>`);
    }
    lines.push(`        </li>`);
  });

  lines.push(`      </ul>`);
  lines.push(`    </nav>`);

  return lines.join("\n");
}

function generateMemoryMapSection(memoryMap: MemoryMap, mmIdx: number): string {
  const lines: string[] = [];

  lines.push(`    <section id="mm-${mmIdx}" class="memory-map">`);
  lines.push(`      <h2>${escapeHtml(memoryMap.displayName || memoryMap.name)}</h2>`);
  if (memoryMap.description) {
    lines.push(`      <p class="description">${escapeHtml(memoryMap.description)}</p>`);
  }

  lines.push(`      <div class="properties">`);
  lines.push(`        <div class="property"><span class="label">Address Unit Bits:</span> ${memoryMap.addressUnitBits}</div>`);
  if (memoryMap.shared !== undefined) {
    lines.push(`        <div class="property"><span class="label">Shared:</span> ${memoryMap.shared ? "Yes" : "No"}</div>`);
  }
  lines.push(`      </div>`);

  memoryMap.addressBlocks?.forEach((ab, abIdx) => {
    lines.push(generateAddressBlockSection(ab, mmIdx, abIdx));
  });

  lines.push(`    </section>`);

  return lines.join("\n");
}

function generateAddressBlockSection(addressBlock: AddressBlock, mmIdx: number, abIdx: number): string {
  const lines: string[] = [];
  const baseAddr = parseNumber(addressBlock.baseAddress);
  const range = parseNumber(addressBlock.range);

  lines.push(`      <section id="ab-${mmIdx}-${abIdx}" class="address-block">`);
  lines.push(`        <h3>${escapeHtml(addressBlock.displayName || addressBlock.name)}</h3>`);
  if (addressBlock.description) {
    lines.push(`        <p class="description">${escapeHtml(addressBlock.description)}</p>`);
  }

  lines.push(`        <div class="properties">`);
  lines.push(`          <div class="property"><span class="label">Base Address:</span> <code>${toHex(baseAddr, 8)}</code></div>`);
  lines.push(`          <div class="property"><span class="label">Range:</span> <code>${toHex(range, 8)}</code> (${range} bytes)</div>`);
  lines.push(`          <div class="property"><span class="label">Width:</span> ${addressBlock.width} bits</div>`);
  lines.push(`          <div class="property"><span class="label">Usage:</span> ${addressBlock.usage}</div>`);
  lines.push(`        </div>`);

  // Registers table
  if (addressBlock.registers && addressBlock.registers.length > 0) {
    lines.push(`        <h4>Registers</h4>`);
    lines.push(`        <table class="register-table">`);
    lines.push(`          <thead>`);
    lines.push(`            <tr>`);
    lines.push(`              <th>Address</th>`);
    lines.push(`              <th>Name</th>`);
    lines.push(`              <th>Size</th>`);
    lines.push(`              <th>Description</th>`);
    lines.push(`            </tr>`);
    lines.push(`          </thead>`);
    lines.push(`          <tbody>`);

    addressBlock.registers
      .sort((a, b) => parseNumber(a.addressOffset) - parseNumber(b.addressOffset))
      .forEach((reg) => {
        lines.push(generateRegisterRow(reg, baseAddr));
      });

    lines.push(`          </tbody>`);
    lines.push(`        </table>`);
  }

  lines.push(`      </section>`);

  return lines.join("\n");
}

function generateRegisterRow(register: Register, baseAddr: number): string {
  const lines: string[] = [];
  const offset = parseNumber(register.addressOffset);
  const absAddr = baseAddr + offset;

  lines.push(`            <tr class="register-row">`);
  lines.push(`              <td><code>${toHex(absAddr, 8)}</code></td>`);
  lines.push(`              <td><strong>${escapeHtml(register.displayName || register.name)}</strong></td>`);
  lines.push(`              <td>${register.size} bits</td>`);
  lines.push(`              <td>${escapeHtml(register.description || "-")}</td>`);
  lines.push(`            </tr>`);

  // Fields
  if (register.fields && register.fields.length > 0) {
    lines.push(`            <tr class="fields-row">`);
    lines.push(`              <td colspan="4">`);
    lines.push(`                <div class="fields-container">`);
    lines.push(`                  <h5>Fields</h5>`);
    lines.push(`                  <table class="field-table">`);
    lines.push(`                    <thead>`);
    lines.push(`                      <tr>`);
    lines.push(`                        <th>Bits</th>`);
    lines.push(`                        <th>Name</th>`);
    lines.push(`                        <th>Access</th>`);
    lines.push(`                        <th>Description</th>`);
    lines.push(`                      </tr>`);
    lines.push(`                    </thead>`);
    lines.push(`                    <tbody>`);

    register.fields
      .sort((a, b) => b.bitOffset - a.bitOffset)
      .forEach((field) => {
        const access = getFieldAccess(field);
        const bitRange = field.bitWidth === 1
          ? `[${field.bitOffset}]`
          : `[${field.bitOffset + field.bitWidth - 1}:${field.bitOffset}]`;

        lines.push(`                      <tr>`);
        lines.push(`                        <td><code>${bitRange}</code></td>`);
        lines.push(`                        <td><strong>${escapeHtml(field.displayName || field.name)}</strong></td>`);
        lines.push(`                        <td><span class="access-badge access-${access}">${access.toUpperCase()}</span></td>`);
        lines.push(`                        <td>${escapeHtml(field.description || "-")}</td>`);
        lines.push(`                      </tr>`);
      });

    lines.push(`                    </tbody>`);
    lines.push(`                  </table>`);
    lines.push(`                </div>`);
    lines.push(`              </td>`);
    lines.push(`            </tr>`);
  }

  return lines.join("\n");
}

function getStyles(theme: "light" | "dark"): string {
  const isDark = theme === "dark";
  const bg = isDark ? "#1a1a1a" : "#ffffff";
  const fg = isDark ? "#e0e0e0" : "#333333";
  const border = isDark ? "#333333" : "#dddddd";
  const cardBg = isDark ? "#252525" : "#f9f9f9";
  const primary = isDark ? "#60a5fa" : "#3b82f6";

  return `
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      line-height: 1.6;
      color: ${fg};
      background: ${bg};
      padding: 20px;
    }
    header {
      background: ${cardBg};
      padding: 30px;
      border-radius: 8px;
      margin-bottom: 30px;
      border: 1px solid ${border};
    }
    h1 { font-size: 2em; margin-bottom: 10px; color: ${primary}; }
    h2 { font-size: 1.5em; margin: 30px 0 15px; color: ${primary}; }
    h3 { font-size: 1.3em; margin: 25px 0 12px; }
    h4 { font-size: 1.1em; margin: 20px 0 10px; }
    h5 { font-size: 1em; margin: 15px 0 8px; font-weight: 600; }
    .subtitle { color: #888; font-size: 1.1em; }
    .meta { margin: 15px 0; font-size: 0.9em; display: flex; gap: 20px; flex-wrap: wrap; }
    .description { margin-top: 15px; color: #666; }
    .toc {
      background: ${cardBg};
      padding: 20px;
      border-radius: 8px;
      margin-bottom: 30px;
      border: 1px solid ${border};
    }
    .toc ul { list-style: none; padding-left: 20px; }
    .toc a { color: ${primary}; text-decoration: none; }
    .toc a:hover { text-decoration: underline; }
    .memory-map, .address-block {
      background: ${cardBg};
      padding: 25px;
      border-radius: 8px;
      margin-bottom: 25px;
      border: 1px solid ${border};
    }
    .address-block { margin-left: 20px; }
    .properties {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
      gap: 10px;
      margin: 15px 0;
    }
    .property { padding: 8px; background: ${bg}; border-radius: 4px; }
    .label { font-weight: 600; margin-right: 8px; }
    table {
      width: 100%;
      border-collapse: collapse;
      margin: 15px 0;
      background: ${bg};
    }
    th, td {
      padding: 12px;
      text-align: left;
      border: 1px solid ${border};
    }
    th {
      background: ${isDark ? "#2a2a2a" : "#f0f0f0"};
      font-weight: 600;
    }
    .register-row { background: ${bg}; }
    .fields-row { background: ${cardBg}; }
    .fields-container { padding: 15px; }
    .field-table { font-size: 0.9em; }
    code {
      font-family: 'Courier New', monospace;
      background: ${isDark ? "#2a2a2a" : "#f0f0f0"};
      padding: 2px 6px;
      border-radius: 3px;
      font-size: 0.9em;
    }
    .access-badge {
      display: inline-block;
      padding: 2px 8px;
      border-radius: 3px;
      font-size: 0.85em;
      font-weight: 600;
    }
    .access-read-write { background: #10b981; color: white; }
    .access-read-only { background: #3b82f6; color: white; }
    .access-write-only { background: #f59e0b; color: white; }
    footer {
      text-align: center;
      margin-top: 50px;
      padding: 20px;
      color: #888;
      font-size: 0.9em;
    }
  </style>`;
}

function escapeHtml(text: string): string {
  const map: Record<string, string> = {
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': "&quot;",
    "'": "&#039;",
  };
  return text.replace(/[&<>"']/g, (m) => map[m]);
}
